[dev]
framework = 'astro'
command = 'astro dev'
targetPort = 3000

[[edge_functions]]
function = 'wakatime'
path = '/api/wakatime'

[[edge_functions]]
function = 'theme'
path = '/*'

[[edge_functions]]
function = 'redirect'
path = '/*'

[[edge_functions]]
function = 'middleware'
path = '/*'

[[headers]]
for = '/assets/*'
[headers.values]
Cache-Control = 'public, max-age=31536000, immutable'

[[headers]]
for = '/static/*'
[headers.values]
Cache-Control = 'public, max-age=86400'
